# Generated by Django 5.0.1 on 2024-03-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0002_login_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='addshow',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
